### PR TITLE
Compression

### PR DESCRIPTION
**Pull request by lrauschning**
Crashes when testing locally, but might be related to some cluster issues.
Opening to see what the CI says.

### CODE REVIEW

**Comment by lrauschning** [comment]
Gah, another template update ruins the lint.
@JoseEspinosa any way to lint against the old version of the template? Otherwise I can look into merging the template into the branch this week, but not sure I have the time...

**Comment by luisas** [comment]
> Gah, another template update ruins the lint. @JoseEspinosa any way to lint against the old version of the template? Otherwise I can look into merging the template into the branch this week, but not sure I have the time...

I can do the template merge today or tomorrow :)

**Comment by JoseEspinosa** [comment]
> Gah, another template update ruins the lint. @JoseEspinosa any way to lint against the old version of the template? Otherwise I can look into merging the template into the branch this week, but not sure I have the time...

I saw @luisas already took care of it, anyway just to mention that it is not possible to run against an old version of the template but that this is something in the pipe now and will be probably possible in the next big release of tools (`3.0`).

**Comment by lrauschning** [comment]
Works, just need to update the pigz module (wasn't handling metas for some reason).
Will open a PR for that to nf-core/modules.

**Review by luisas — APPROVED** [review]
Fantastic job Leon!!

**Pull request merged**
