### PR TITLE
delete fastqc, not required anywhere

### PR DESCRIPTION
**Pull request by lrauschning**
FastQC doesn't seem to be required by any of our workflows, this PR deletes it.

### CODE REVIEW

**Review by JoseEspinosa — CHANGES_REQUESTED** [review]
Did not realise about the merge errors, why are we having them? Needs to be fixed before merging

**Comment by lrauschning** [comment]
Not sure what was causing that, but something about the `CUSTOM_DUMPSOFTWAREVERSIONS` was weird.
fixed the conflicts locally, should be fine?

**Comment by lrauschning** [comment]
Okay getting a very weird S3 error locally, but on the CI it works

**Review by luisas — APPROVED** [review]

**Review by JoseEspinosa — APPROVED** [review]
LGTM!

**Pull request merged**
